const LAB_EXECUTION_REPORT_URL = 'http://localhost:3009/report';
const MOCHA_STATUS = {
  PASSED: 'passed',
  FAILED: 'failed'
};

const REPORTING_TEST_STATUS = {
  PASSED: 'PASSED',
  FAILED: 'FAILED',
  UNKNOWN: 'UNKNOWN',
  BLOCKED: 'BLOCKED'
};

const REPORTING_COMMAND_STATUS = {
  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE'
};

module.exports = {
  LAB_EXECUTION_REPORT_URL,
  MOCHA_STATUS,
  REPORTING_COMMAND_STATUS,
  REPORTING_TEST_STATUS
};
